### ISSUE TITLE
Sort album list alphabetically

### ISSUE THREAD

**Issue by ghost** [sebastianw/gallery2picasa#19]
Upload Album "Galleri - Uldum hÃ¸jskole - EfterÃ¥r 2005 - Andre Billeder"? [y/N/a]n
Upload Album "Galleri - Rejser - Kleinwalsertal i Ã¸string"? [y/N/a]n
Upload Album "Galleri - Rejser - Erik og Henriette pÃ¥ tur. - Film"? [y/N/a]n
Upload Album "Galleri - Rejser - Lena og Anders pÃ¥ jordomrejse - Costa Rica"? [y/N/a]n
Upload Album "Galleri - Familie - Stormen pÃ¥ vitskÃ¸l"? [y/N/a]n
Upload Album "Galleri - Uldum hÃ¸jskole - ForÃ¥r 2006"? [y/N/a]n
Upload Album "Galleri - Rejser - Erik og Henriette pÃ¥ tur. - Belize"? [y/N/a]n
Upload Album "Galleri - Rejser - Backpacker tur 2006 - Thailand"? [y/N/a]n
Upload Album "Galleri - Uldum hÃ¸jskole - EfterÃ¥r 2005 - Anne k"? [y/N/a]n
Upload Album "Galleri - Uldum hÃ¸jskole - EfterÃ¥r 2005 - Mie - 16,12,05"? [y/N/a]a
CREATING ALBUM [Galleri - Rejser - Erik og Henriette pÃ¥ tur. - Argentina] []
        CREATING Item [F:IMG_5090.JPG] [T:Saa er vi paa city tur i Buens Aires.] [S:Saa er vi paa city tur i Buens Aires.] [K:]
        CREATING Item [F:IMG_5091.JPG] [T:Museum.] [S:Museum.] [K:]
        CREATING Item [F:IMG_5092.JPG] [T:Vatikanets ambassade i Argentina.] [S:Vatikanets ambassade i Argentina.] [K:]
^C

-0 option dosent work as it should, mismatch between selected album and actually uploaded albums.

seems the problem exists with both use of combinations  n/y and /n/a

**Comment by sebastianw** [comment]
Hi,

The Argentinia Subalbum is not in the list of albums you pressed "n" for and you pressed "a" so it gets uploaded along with the rest. The albums change order when uploading at the moment (as it is a hash with unordered keys) but only the ones you select should get uploaded. I'll fix the ordering but that should be purely cosmetic.

**Comment by ghost** [comment]
Nice, but it gives me some problems when I have to rerun the script after a crash to resume the upload.

**Comment by sebastianw** [comment]
The ordering needs to be fixed so that it's always the same (preferably alphabetically). I'll see what I can do about it.
