### ISSUE TITLE
gdata.photos.service.GooglePhotosException: (601, ...

### ISSUE THREAD

**Issue by garyploski** [sebastianw/gallery2picasa#23]
Gallery version = 2.3 core 1.3.0

I've attempted the gallery2picasa script with gdata 2.0.17 and 2.0.14. Both end up with the same error...

gdata.photos.service.GooglePhotosException: (601, "Found , not path name or object with a .read() method", 'filename_or_handle must be a path name or a file-like object')

---

[~]# python2.6 public_html/cgi-bin/gallery2picasa-master/gallery2picasa.py -b XXXXXX -d XXXXXX -a XXXXXX -u XXXXXX -p XXXXXX
Upload Album ".com-gallery - 1975-1992"? [y/N/a]a
CREATING ALBUM [1975-1992] [Pix way back from 1975-1992]
    CREATING Item [F:j_amp_g smithsonian trip.jpg] [T:j&g smithsonian trip] [S:Jeff Pinto and I posing next to me pop's plane at the Smithsonian.] [K:]
Traceback (most recent call last):
  File "public_html/cgi-bin/gallery2picasa-master/gallery2picasa.py", line 275, in <module>
    main(sys.argv)
  File "public_html/cgi-bin/gallery2picasa-master/gallery2picasa.py", line 262, in main
    raise e
gdata.photos.service.GooglePhotosException: (601, u'Found /var/local/g2data/albums/1975-1992/j_amp_g smithsonian trip.jpg, not path name or object with a .read() method', '`filename_or_handle` must be a path name or a file-like object')

**Comment by sebastianw** [comment]
Hi, was does `ls -la "/var/local/g2data/albums/1975-1992/j_amp_g smithsonian trip.jpg"` show?

**Comment by garyploski** [comment]
Thanks for your reply.

[~]# ls -la "/var/local/g2data/albums/1975-1992/j_amp_g smithsonian trip.jpg"
/bin/ls: /var/local/g2data/albums/1975-1992/j_amp_g smithsonian trip.jpg: No such file or directory

When I try to ls var in any way I get the 'No such file or directory' message. I may be doing something wrong or I don't have proper permissions.

Just in case I ran this...
[~]# ls -la public_html/gallery/g2data/albums/1975-1992/
total 324
drwxr-xr-x  2 XXXXXX XXXXXX   4096 Oct 28  2005 ./
drwxr-xr-x 20 XXXXXX XXXXXX   4096 Sep  7  2009 ../
-rwxr-xr-x  1 XXXXXX XXXXXX 187678 Oct 28  2005 j_amp_g\ smithsonian\ trip.jpg*
-rwxr-xr-x  1 XXXXXX XXXXXX 126392 Oct 28  2005 spidey-n-me.jpg*

Could the spaces be causing an issue?

**Comment by sebastianw** [comment]
Indirectly, yes. Somehow (I don't know how) gallery put backslashes (`\`) into your file name(s) . Seems like some sort of escaping error when the files where created on disk. Sorry, there is not much for the script to do as the file names in the database and on the disk differ. You could try to fix this and remove the backslashes from your files. I find it strange that gallery would even display these images.
