### ISSUE TITLE
Migration to Oauth2 needed?

### ISSUE THREAD

**Issue by ffainelli** [sebastianw/gallery2picasa#24]
Hi,

I tried to utilize the script (which works great by the way) but encountered the following error while trying to authenticate:

Traceback (most recent call last):
  File "./gallery2picasa.py", line 278, in <module>
    main(sys.argv)
  File "./gallery2picasa.py", line 213, in main
    galbum = create_google_album(pws, album, atitle, privacy)
  File "./gallery2picasa.py", line 93, in create_google_album
    raise e
gdata.photos.service.GooglePhotosException: (403, 'Forbidden', 'Modification only allowed with api authentication.')

Does that ring a bell?

**Comment by ffainelli** [comment]
Looks like redleader36/gallery2picasa has it already, might be nice to merge this back into your repository.

**Comment by sebastianw** [comment]
As I neither use Picasa or Gallery2 anymore I'm not doing any active work on this. I looked at the forked repository but I'm not convinced by a few changes so I'll not merge it back. But feel free to use it.
