### ISSUE TITLE
TypeError: encode() argument 1 must be string, not None 

### ISSUE THREAD

**Issue by ghost** [sebastianw/gallery2picasa#5]
/sebastianw-gallery2picasa-7de09a6$ sudo ./gallery2picasa.py -b gallery -a xxxxxx.p -u e@mail.com -p xxxxxxx -d gallery -g /var/www/gallery/g2data -y private -o false >> gallery.log
Traceback (most recent call last):
  File "./gallery2picasa.py", line 215, in <module>
    main(sys.argv)
  File "./gallery2picasa.py", line 151, in main
    galbum = create_google_album(pws, album, privacy)
  File "./gallery2picasa.py", line 71, in create_google_album
    print strout.encode(sys.stdout.encoding, 'replace')
TypeError: encode() argument 1 must be string, not None

**Comment by ghost** [comment]
/sebastianw-gallery2picasa-7de09a6$ sudo ./gallery2picasa.py -b gallery -a xxxxxx.p -u e@mail.com -p xxxxxxx -d gallery -g /var/www/gallery/g2data -y private -o false >> gallery.log

no errors now, but there is nothing in the log...

**Comment by sebastianw** [comment]
The standard output is buffered by python. You should see the output in the logfile eventually when the program finishes or when you interrupt it. As a workaround if you really need to see it instantly, you could try using python -u: sudo python -u ./gallery2picasa.py ....

**Comment by ghost** [comment]
Thanks.

I will try that :-)

2011/10/29 Sebastian Wiesinger <
reply@reply.github.com>

> The standard output is buffered by python. You should see the output in
> the logfile eventually when the program finishes or when you interrupt it.
> As a workaround if you really need to see it instantly, you could try using
> python -u: sudo python -u ./gallery2picasa.py ....
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sebastianw/gallery2picasa/issues/5#issuecomment-2564464

## 

Med venlig hilsen/Best regards
Kre Baastrup
Tel. 61557464
