### ISSUE TITLE
Request: get a list of albums

### ISSUE THREAD

**Issue by ghost** [sebastianw/gallery2picasa#7]
Here is some suggestions.

Is it possible to get a list of album in Gallery2 into a text file like this:

Summer party
Christmas
2007 pictures

1.
and then run the script again with the new (edited) text file as a parameter.

This would make it possible to get a long list of albums edit the list of what you dont  need and start the script up again without having to confirm every single album.
1. (maybe better?)
   or maybe a reverse the selection , so you have to confirm every album, and then the script first start migrating after all is choosen?

**Comment by sebastianw** [comment]
I implemented the second option, you can now confirm every album before the upload is starting.
