### ISSUE TITLE
No log file generated(too big files)

### ISSUE THREAD

**Issue by ghost** [sebastianw/gallery2picasa#9]
Hi it dosent look like the script creates a log file with all the skiped videos.

**Comment by sebastianw** [comment]
The script doesn't create a logfile by itself at all. If you want all the errors and the output in a logfile do something like:

`>script.log 2>&1`

**Comment by ghost** [comment]
Oh so there is no logging of the video it skips, because if the size?
that would be a nice feature, to have a skiped files log...

**Comment by sebastianw** [comment]
The script output should mention the video file, like normal... You posted the output to gh-8 so it's there.

**Comment by ghost** [comment]
An easy way of creating a logfil.

import subprocess, os, sys

sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)

tee = subprocess.Popen(["tee", "log.txt"], stdin=subprocess.PIPE)
os.dup2(tee.stdin.fileno(), sys.stdout.fileno())
os.dup2(tee.stdin.fileno(), sys.stderr.fileno())

**Comment by sebastianw** [comment]
As I wrote above, you can use normal shell redirection to create a log file. There is no need for the program to do it.

**Comment by ghost** [comment]
yes but if I try to do a /gallery2picasa............. | tee file.log nothing happens.

seems like "|" is not allowed.

**Comment by sebastianw** [comment]
I cannot reproduce the issue. It works on my end.

**Comment by ghost** [comment]
What if you want to interact with the script while logging?
Den 29/11/2011 21.58 skrev "Sebastian Wiesinger" <
reply@reply.github.com
